### ISSUE TITLE
Wiki auf dem originalen Repo für uns freischalten?

### ISSUE THREAD

**Issue by Asysob** [puppe/campingtrip#2]
Schnelle Kommunikation mit Empfehlungen usw., d.h. praktisch alle Meta-Diskussion, ist im Wiki vermutlich besser aufgehoben?

**Comment by Asysob** [comment]
Dabei müßte man uns als Contributor eintragen, damit wir im Wiki produktiv werden können (es ist wirklich zäh, wenn ich alle meinen Ideen über eine Datei im Repo committen und pushen muß). Mit etwas Glück kann man uns ja das Schreib-Recht auf dem Repo selber verweigern? Geht das?

**Comment by puppe** [comment]
Man kann einstellen, dass jeder das Wiki bearbeiten darf. Das habe ich jetzt getan.

**Comment by Asysob** [comment]
Alles klar. Vielen Dank! Ich probiere es gleich mal aus.
